### ISSUE TITLE
Non-issue: Works great on non-retina screen

### ISSUE THREAD

**Issue by insidegui** [danieljfarrell/DFColorWell#1]
I just want to let you know that I've tested this on a Mid 2011 iMac and It looks great, you may want to remove the warning from your readme ;)

**Comment by danieljfarrell** [comment]
Oh fantastic news. Can you post a screenshot? Would be interested in seeing how the border is drawn and whether it is crisp or a fuzzy line.

There is one obvious bug that I just realised that I will add to the readme. There is is no disabled state or hidden state! Oops.

**Comment by insidegui** [comment]
There you go
![captura de tela 2015-02-21 as 15 25 49](https://cloud.githubusercontent.com/assets/67184/6315088/f7675f5a-b9dd-11e4-964f-f98d26dacb05.png)

**Comment by danieljfarrell** [comment]
Sorry about this, as you are my only link to a non-retina screen I'm going to ask! Could you select just the control (without popover) and post a really big image so I can see how the border looks. I zoomed in on that image and it looks uneven which is not good.

**Comment by insidegui** [comment]
![captura de tela 2015-02-21 as 16 11 51](https://cloud.githubusercontent.com/assets/67184/6315283/78310090-b9e4-11e4-95b8-7077517307f8.png)
![captura de tela 2015-02-21 as 16 12 13](https://cloud.githubusercontent.com/assets/67184/6315282/783041a0-b9e4-11e4-9991-789152932354.png)

**Comment by danieljfarrell** [comment]
Hmmm... doesn't seem to have rendered quite right actually, the bottom line seems thinner...

**Comment by DarkDust** [comment]
The problem was a fairly typical one: drawing in Cocoa works with infinitely thin lines. When you stroke a path, Cocoa draws to both sides of that infinitely thin line. So to actually fill an on-screen pixel, the stroke path needs to be offset by half-a-pixel. See the pull-request #5 for a solution. Feel free to edit it as you see fit.

**Comment by insidegui** [comment]
@DarkDust correct!

**Comment by danieljfarrell** [comment]
Fixed in pull request 2419a6e546d2ecb4ae9126a5968b697413e10241
