### ISSUE TITLE
Button not enable

### ISSUE THREAD

**Issue by gmcusaro** [danieljfarrell/DFColorWell#16]
At launch the the colorwell button is not enable
<img width="448" alt="enable" src="https://user-images.githubusercontent.com/30832514/35796240-2a52385a-0a5c-11e8-93b9-1f7caf6a5088.png">

**Comment by danieljfarrell** [comment]
I must say this project needs some love and attention, I have not done much with it since I wrote it.

What version of macOS are you using and Xcode?

**Comment by gmcusaro** [comment]
Thanks for your reply!
This project is really interesting. Can you update it?

MacOS 10.12.6 Xcode 8.3.3 and MacOS 10.13.3 Xcode 9.2

**Comment by danieljfarrell** [comment]
I would love too but it’s had to find time these days, and my interest have shifted a bit. But you are right, I would like this to just work out of the box too. It’s a fairly nice objc project. 

I’m not yet on macos 10.12 and won’t be for sometime. But I will run it on what I have and see if I can reproduce this.

**Comment by gmcusaro** [comment]
Ok thanks!

**Comment by danieljfarrell** [comment]
Fixed in commit 9b5ebb2! Pull from the master branch and you should be set.
